version: '3.7'

services:
  telegram_bot:
    image: telegram-bot-image
    deploy:
      replicas: 1
    secrets:
      - GEMINI_API_KEY
      - TELEGRAM_BOT_TOKEN
    environment:
      GEMINI_API_KEY: /run/secrets/GEMINI_API_KEY
      TELEGRAM_BOT_TOKEN: /run/secrets/TELEGRAM_BOT_TOKEN
    ports:
      - "8443:8443" # Expose port 8443

secrets:
  GEMINI_API_KEY:
    external: true
  TELEGRAM_BOT_TOKEN:
    external: true
